name: scooter_cluster
description: Electric scooter instrument cluster
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  redis: ^4.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  flutter_map: ^6.1.0
  vector_map_tiles: ^7.3.1
  vector_map_tiles_mbtiles: ^1.1.0
  vector_tile_renderer: ^5.2.1
  mbtiles: ^0.4.0
  latlong2: ^0.9.0
  path_provider: ^2.1.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  sqlite3_flutter_libs: ^0.5.32
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  nested: ^1.0.0
  simple_animations: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  source_gen: ^2.0.0
  analyzer: ^7.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/maplight.json
    - assets/mapdark.json
